server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/url_shortener?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
    username: root
    password: 'example'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 minutes in milliseconds
      cache-null-values: false
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

app:
  base-url: http://localhost:8080
  default-expiration-days: 365
  rate-limit:
    window-seconds: 60
    max-requests: 30
